train:
  - order: 'gradient' # chorno means training mini-batches are formed in chronological order
    epoch: 200
    batch_size: 600
    lr: 0.0001
    dropout: 0.1
eval:
  - batch_size: 100
    val_epoch: 100  # the training epoch that start evaluation on the validation set
scope:
  - layer: 2
    neighbor:
      - 25
      - 25
    strategy: 'uniform'
sample:
  - type: 'adapt'
    neighbor: 10
    freq_encode: 'sin'
    keep_dummy_freq: false
    identity_encode: false
    dim_feat: 100
    dim_encode: 100
    feat_norm: false
    neigh_norm: false
    mixer: false
    decoder: 'gat_v2'
    init_gain: 1.0
    unif_bias: True
    lr: 0.0001
    weight_decay: 0
    att_clamp: 20
gnn:
  - arch: 'transformer'
    layer: 2
    att_head: 2
    time_enc: 'learnable'
    dim_time: 100
    dim_out: 100
