train:
  - order: 'gradient'
    epoch: 200
    batch_size: 600
    lr: 0.0001
    dropout: 0.1
eval:
  - batch_size: 600
    val_epoch: 0
scope:
  - layer: 1
    neighbor:
      - 25
    strategy: 'recent'
sample:
  - type: 'adapt'
    neighbor: 10
    freq_encode: 'sin'
    keep_dummy_freq: true
    identity_encode: true
    dim_feat: 100
    dim_encode: 100
    mixer: true
    decoder: 'transformer'
    init_gain: 1.0
    unif_bias: True
    lr: 0.0001
    weight_decay: 0
gnn:
  - arch: 'mixer'
    layer: 1
    time_enc: 'fixed'
    dim_time: 100
    dim_out: 100